### ISSUE TITLE
Error Packaging the Application

### ISSUE THREAD

**Issue by cgascons** [lilili87222/admob-for-flash#26]
Hi, 

First of all thanks for the ANE, I've been implementing it in my project recently and I just found out that when I attempt to package it for release, it just returns an error, at first I use using AIR 16 but I afterwards read it requires AIR 17, so I just downloaded the latest AIR SDK beta (18, build 130) and I'm getting this error:

Error occurred while packaging the application:

dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/ads/AdRequest$ErrorCode;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)
	at com.android.dx.command.dexer.Main.run(Main.java:247)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
1 error; aborting

I'd really appreciate some help.

Cheers!

[EDIT] This happens when using both ANE's (admob_all_in_one_6.12.2.ane and admob_all_in_one_20150519.ane)
[EDIT 2]: Tried with AIR SDK 17 and no luck either.

**Comment by lilili87222** [comment]
have you used any other ane?

**Comment by fraylopez** [comment]
Yep, the same for me. 
I'm using other ANEs

**Comment by cgascons** [comment]
Sorry I forgot to reply to this. Same as fraylopez, it only works with the _without_gps version.
